project/src/main/IntermissionPanelDemo.tscn, project/src/main/hand.gd, project/src/main/maze-level-rules.gd, project/src/main/player-data.gd, project/src/main/word-find-level-rules.gd
Most of these bugs stems from things like "clamp(1. 0.0, 3.0)" or "if
1.0 == 1" returning different values in the released game. I've added
some explicit int casts to address this.
=> Bugs: unhuggable hand, save data, maze glitches

project/src/main/card-control.gd
Increasing the shark timer lets players dissect their mistake.
=> Increased delay after finding a shark.

project/src/main/secret-collect-level-rules.gd
Clicking a red card on the Secret Collect level could reveal a shark who
would immediately change to a frog.
=> Fixed secret collect 'traitor shark' bug

project/src/main/card-control.gd, project/src/main/intermission-panel.gd, project/src/main/maze-level-rules.gd, project/src/main/secret-collect-level-rules.gd
Fixed bug where maze could start with a shark. This is because instead
of trying to render a 'ew' arrow, it would try to render a 'we' arrow
which doesn't exist, resulting in a random arrow. I've added a warning
just in case this happens again.
Secret collect now shows all four arrows upon failing. This might help
players understand to look for those arrows, and that they don't have to
click all four surrounding squares to try and find the arrow.
=> Improvements/bugfixes for Maze, Secret Collect

project/src/main/background.gd, project/src/main/finger-sprite.gd, project/src/main/froggo-level-rules.gd, project/src/main/utils.gd, project/src/main/wiggle-timer.gd
Godot does not support multiline comments, but triple quotes were used as a kludge. I don't like using this kludge anymore.
=> Eliminated triple-quote 'comments'

project/src/main/card-control.gd, project/src/main/ui/menu/clickable-icon.gd, project/src/main/utils.gd
Card textures all have frame sizes of 160x160, so rather than explicitly assigning them we can calculate them with a utility.
=> Auto-assign hframes/vframes for card textures

project/src/demo/level-rules-demo.gd, project/src/main/MainMenuPanel.tscn, project/src/main/gameplay-panel.gd, project/src/main/intermission-panel.gd, project/src/main/level-buttons.gd, project/src/main/main-menu-panel.gd, project/src/main/menu-state.gd, project/src/main/player-data.gd, project/src/main/ui/menu/TutorialButtons.tscn, project/src/main/ui/menu/World1Buttons.tscn
Replaced 'difficulty' with 'mission string'. The first level corresponds to '1-1', and the last level currently corresponds to '3-3' but will eventually be something like '10-3'. Instead of storing the furthest difficulty the player's cleared, we now store all of the mission string outcomes.
The player cannot progress to later worlds until they finish the third level in a world. It is okay if they find all sharks and no frogs, they just have to play it and reach an ending.
Level buttons are now all visible -- since the player has to clear the third level in a world to progress, progression was permanently blocked if those buttons weren't available
=> Mission strings. Block progression.

project/src/main/froggo-level-rules.gd, project/src/main/gameplay-panel.gd, project/src/main/utils.gd
Replaced int(rand_range()) with homebrew randi_range(). int(rand_range()) can theoretically return an int at the top of the range which could cause bugs.
All constants are public.
=> Avoid int(rand_range()). Public constants.

project/src/demo/hand-demo.gd, project/src/main/hand.gd, project/src/main/menu-state.gd
Extracted _end_intermission() method. This method now always restores the hand's biteable fingers to -1, turning the hand back into a pointer.
Improved hand comments. The demo comments were misleading. Added comments describing the rather obscure dual purpose 'biteable fingers' field. Extracted a new 'play_ending' method.
=> Hand refactoring: end intermission, comments

project/src/main/MainMenu.tscn, project/src/main/MenuState.tscn, project/src/main/menu-state.gd
This avoids potential complications when levels are interrupted or paused, because these timers can be easily cleaned up. Yield statements can't really be interrupted, and anonymous timers can't really be cleaned up.
=> Replaced 'yield' statements with timers and signals.

project/src/main/froggo-level-rules.gd
Froggo level rules now define a list of words (freg, sark, ohno) which are later converted into 'aliaxes' (fRE+). There are a few utility methods for handling aliaxes. This makes the word lists more maintainable, avoiding bugs where someone might accidentally define a troll frog word of 'freg/frog'.
=> Froggo word/aliax split

project/project.godot, project/src/main/RunningFrog.tscn, project/src/main/creature-behavior.gd, project/src/main/frog-chase-behavior.gd, project/src/main/intermission-panel.gd, project/src/main/running-frog.gd, project/src/main/running-shark.gd
In their current implementation, frogs always chase the cursor but they'll eventually need to do multiple things. I've split out the 'CreatureBehavior' with a single implementation, 'FrogChaseBehavior'. This encapsulates the behavior of chasing the cursor, and other scripts will eventually extend CreatureBehavior with other behaviors such as dancing.
This change only affects frogs for now -- it is still heavily in flux, and sharks only do one thing right now. Once it is more mature or there is a need for it, I will apply the change to sharks.
Removed unused 'old_frame' field.
=> Split out 'CreatureBehavior' from 'RunningFrog'

project/src/main/menu-state.gd, project/src/main/music-player.gd
Instead of MusicPlayer playing music on startup, MenuState now plays music on startup. This prevents music from playing during demos.
=> Disable MusicPlayer from playing music during demos.

project/src/main/menu-state.gd
Instead of our ending logic waiting 4 seconds and then picking an appropriate ending, it now picks an ending which waits 4 seconds. This is important because we will soon have endings which do not include this wait. Pushing this delay down further gives different endings the option of having shorter delays or no delays at all.
=> End intermission timer tweak.

project/src/demo/intermission-panel-demo.gd, project/src/main/MusicPlayer.tscn, project/src/main/music-player.gd
Added fade_in() and get_playback_position() methods to music api. This is useful for synchronizing dances or forcing music to fade in, instead of playing abruptly after a cutscene.
Alphabetized 'WereGonnaEatYouUp' AudioStreamPlayer node.
Added music toggle to IntermissionPanelDemo.
=> Music api: fade_in, get_playback_position

project/src/main/IntermissionPanel.tscn
Before, resizing the window would cause intermission panel creatures to asymmetrically gravitate towards the top and left corners of the panel. This is an extremely subtle annoyance, but it carries more gravity with the upcoming frog dance where we really want characters to stay centered.
=> Center intermission panel creatures.

project/src/main/intermission-panel.gd
Sharks and frogs were spawning too far down and too the right, sometimes even spawning in a visible location on the left edge. Additionally, their spawn locations were offset even further if the window was enlarged.
Frogs and sharks now spawn in an appropriate location.
=> Fix creature spawn location.

project/src/main/RunningFrog.tscn, project/src/main/frog-dance-behavior.gd
This bug resulted in frogs occasionally running too far and snapping back into place.
The old logic used a timer so the frog would run for 8.812 seconds and stop, and then we'd set their position to their target. Sometimes this was off by as much as 60 pixels, resulting in an unpleasant snapping effect.
The new logic uses the frog's position, so the frog runs until they're within a certain radius, and until their velocity would take them further away if they continued running. This is more accurate -- it has theoretical bugs if the radius is too small or there are hiccups where _process() is called with large delta values. But in practice, it is doing what we want.
=> Fixed bug where dancing frogs could overrun their target.

project/src/main/music-player.gd
It's unusual that it wouldn't play all the way through anyways, but this can happen during the intermission panel demo.
=> Dance song no longer saves position.

project/src/main/intermission-panel.gd
This 'random spawn point' logic is now centralized in one place, not copy/pasted for frogs and sharks.
=> Extracted copy/paste spawn_point logic

project/src/demo/intermission-panel-demo.gd
IntermissionPanelDemo could no longer show frog cards, because there were no cards on screen.
=> Fixed IntermissionPanelDemo's 'show frog card' key.

project/src/main/ui/CheatCodeDetector.tscn
There is a bug in Godot where opening and closing a .tscn causes completely random changes to happen about 1% of the time.
In commit 716bd98, I opened and saved all .tscn files to revert the signal order to Godot's preferred order. This randomly caused two AudioStreamPlayers to have their bus reverted from the "Sfx" bus to the default "Master" bus.
I've reverted the change.
=> Reverted 'cheat code sound bus' bug introduced by evil Godot gnomes

project/src/main/froggo-level-rules.gd, project/src/main/utils.gd, project/src/test/test-utils.gd
Godot #54869 removes String.erase() in Godot 4. This branch reimplements it as a utility method on our Utils class.
=> Replaced 'String.erase()' with utility method

project/src/demo/LevelRulesDemo.tscn, project/src/main/maze-level-rules.gd, project/src/main/pattern-memory-level-rules.gd, project/src/main/running-frog.gd, project/src/main/word-find-level-rules.gd
PatternMemoryLevel had a bug where it was checking 'randf() > shark_chance', leading to an inverse relationship where a higher shark chance resulted in fewer sharks.
I've changed other parts of code to avoid this as well; 'randf() > 0.2' is a misleading and confusing way of coding an 80% chance.
=> Fixed 'randf() < foo' references.

project/src/main/frog-dance-behavior.gd, project/src/main/intermission-panel.gd, project/src/main/running-frog.gd, project/src/main/running-shark.gd
Godot 4 removes the ability for scripts to update their own properties without invoking setters and their corresponding side effects, and it's a better design anyway so I'm applying it to Godot 3 as well.
=> set_soon_position() no longer updates the frog's position.

project/src/main/Background.tscn, project/src/main/MusicPlayer.tscn, project/src/main/background.gd, project/src/main/music-player.gd
Godot 4 is removing the Tween node, so I've replaced all Tween references with SceneTreetWeens.
=> Replace Tween with SceneTreeTween

project/src/main/fruit-maze-rules.gd, project/src/main/level-rules.gd, project/src/main/maze-level-rules.gd, project/src/main/pattern-memory-level-rules.gd, project/src/main/secret-collect-level-rules.gd, project/src/main/utils.gd
Godot 3.x let us treat integers/arrays/dictionaries as boolean values, but Godot 4.x doesn't let us do that anymore. In preparation for the Godot 4 upgrade, I'm replacing these references.
Removed redundant integer division warning in frodoku-level-rules.gd.
=> Replaced 'if foo' with 'if not foo.empty()'

project/src/main/IntermissionPanel.tscn, project/src/main/intermission-panel.gd
This was broken during the Godot 4 upgrade.
The automatic Godot 4 upgrades replace any 'YSort' nodes with generic 'Node2D' nodes, but do not enable the 'y_sort_enabled' property.
=> Restored intermission panel ysort.

project/src/demo/LevelRulesDemo.tscn, project/src/main/IntermissionPanel.tscn, project/src/main/MainMenu.tscn, project/src/main/MainMenuPanel.tscn, project/src/main/ui/menu/rounded-style-box.tres
Rounded UI corners were disabled during the Godot 4.x upgrade. It unassigned our theme overrides.
Closes #185.
=> Restoring rounded UI corners.

project/project.godot
Workaround for Godot #71350. The Vulkan rendering backends are complex and require a long time to start (about 10 seconds). The resulting graphical enhancements are worth it, but during development I prefer the faster loading times of the Compatibility renderer.
https://github.com/godotengine/godot/issues/71350
=> Update rendering mode to 'Compatibility'.

delint.sh, project/src/main/word-find-level-rules.gd
At a glance, stuff like 'randf() > 0.35' looks like a 35% chance and 'randf() < 1.0' looks like a 100% chance. It takes a little more thought and mental arithmetic to figure out what it's actually doing. 'randf() <= 0.65' is easier to read.
Added delinting rule for functions missing type hint. No frog finder methods are missing type hints.
=> Refactor: Avoid 'randf >', functions missing type hint

project/project.godot, project/src/main/card-control.gd, project/src/main/music-player.gd, project/src/main/utils.gd
Our old code was comparing a float value 'MIN_VOLUME' using ==. I've changed it to use 'is_equal_approx'
Fixed warning which popped up in the editor in 'assign_card_texture' complaining because the texture was null.
Fixed warning about blender file imports.
Removed remaining Godot #58285 comment.
=> Refactoring: min_volume, blender, texture.get_width

project/src/main/card-control.gd
64c8db62416892 broke a lot of code because it called show_front before the onready variables were initialized. We fixed this in the short term by moving the show_front calls after the card is initialized, but a better design is to have a field like front_shown and back_shown which you set, and which then show the appropriate sprite in _ready().
=> Refactor: CardControl.shown_face

project/src/main/ui/cheat-code-detector.gd
The contract for String.right() changed from Godot 3.x to Godot 4.x
=> Fixed CheatCodeDetector's length math

project/src/main/comic/comic-letter.gd, project/src/main/comic/comic-title.gd
Comic titles constantly change their frames and materials. Some of this seems unavoidable (I think Godot recreates materials in the editor constantly if you set the 'Local To Scene' flag, or something like that), but I've made some changes that seem to help slightly.
ComicLetter no longer stores its LetterNodes. This was introducing edge cases in the editor where its title and its nodes were out of sync.
=> Reduce churn for ComicTitle scene

project/src/demo/IntermissionPanelDemo.tscn, project/src/demo/LevelRulesDemo.tscn, project/src/main/CardControl.tscn, project/src/main/GameplayPanel.tscn, project/src/main/IntermissionPanel.tscn, project/src/main/MainMenu.tscn, project/src/main/MainMenuPanel.tscn, project/src/main/card-control.gd, project/src/main/card-shadows.gd, project/src/main/comic-manager.gd, project/src/main/comic/World2ComicPage.tscn, project/src/main/comic/comic-conductor.gd, project/src/main/gameplay-panel.gd, project/src/main/intermission-panel.gd, project/src/main/level-cards.gd, project/src/main/levels/frodoku-rules.gd, project/src/main/levels/froggo-rules.gd, project/src/main/levels/fruit-maze-rules.gd, project/src/main/levels/level-rules.gd, project/src/main/levels/maze-rules.gd, project/src/main/levels/pattern-memory-rules.gd, project/src/main/levels/secret-collect-rules.gd, project/src/main/levels/word-find-rules.gd, project/src/main/menu-state.gd
Godot 4 lets you export a node type directly, handling the nodepath behind the scenes.
=> Removed NodePath exports.

project/src/main/RunningFrog.tscn, project/src/main/dance-animations.gd
When transitioning from Godot 3 to Godot 4, I incorrectly added a remove_animation_library() call instead of getting the animation library and removing the appropriate animation. There was also an array cast error.
=> Fixed 'dance flip logic' for Godot 4

project/src/main/levels/frodoku-rules.gd
This was broken in b297a704 when the methods were renamed without updating all of the references.
=> Fixed errors in Frodoku level.

project/src/main/RunningFrog.tscn, project/src/main/RunningShark.tscn, project/src/main/running-shark.gd
Aligned RunningShark offset so their x/y coordinate aligns with their feet. This allows y-sort to work as expected, and also allows for some cleaner collision logic in an upcoming commit.
=> RunningShark offset. RunningFrog reset frame.

project/project.godot
The 'Forward+' renderer used to take about 10 seconds to launch, but they've seemingly improved its performance. It sometimes takes 10 seconds to launch but after the first launch, it's fast.
=> Change renderer to 'forward'; it is no longer slow

project/project.godot, project/src/main/beach-ball-tweak.gd
Changed clicked_ball_distance to a float to avoid a narrowing conversion warning.
=> Alphabetize autoload singletons. Narrowing conversion warning.

generate-export-presets.sh
Instead of versions like '0.7501', our version number generation logic now generates numbers like '1.21'. The old system was inherited from Turbo Fat.
=> Changed version number generation to '1.21'

project/src/main/intermission-panel.gd
IntermissionPanel and BeachBallTweak reference each other, because SceneTreeTweaks describe how to modify an IntermissionPanel and IntermissionPanel includes a list of all scene tree tweaks. This circular reference makes it so that BeachBallTweak (and all other tweaks) can not be opened in the editor, because of Godot #74253 (https://github.com/godotengine/godot/issues/74253)
I've resolved the circular reference by having these scenes initialized at runtime with a 'load' command, rather than when the scene is loaded with a 'preload' command.
=> Workaround for circular reference error in IntermissionPanel.

project/src/main/CardControl.tscn, project/src/main/card-control.gd
This is useful for things like dynamically generating titles within the editor. Now we can preview that the code works without launching the game, because the cards will change in the editor.
=> CardControl is now a tool script.

project/src/main/intermission-panel.gd
Fixed a bug where IntermissionPanel.reset() enabled tweaks when invisible. This meant that after finishing a beach level, you could click around and invisible beach ball noises would play. It was kind of fun in a way but still glitchy.
=> Bug: IntermissionPanel.reset() enabled tweaks when invisible.

project/src/main/player-data.gd
When the music was configured to 'off', it still played briefly when the game started up because the world index was set first (triggering music) before the music preference was set (setting it to off.)
This wouldn't be noticable, except that the music fades out so you can actually hear it for 0.1 seconds or so.
=> Bug: Music played for a fraction of a second when 'off'

project/src/demo/ComicLetterDemo.tscn, project/src/main/comic/comic-letter.gd, project/src/main/wiggle-sprite.gd
This causes unnecessary churn in our .tscn files, and more specifically was causing ComicLetterDemo to change every time it was saved
=> Avoid randomizing comic letter frames in the editor

project/src/main/card-control.gd, project/src/main/player-data.gd
Removed unnnecessary 'static called on instance' warning; this method is now calling a static function correctly.
=> Fixed 'static called on instance' warnings.

project/src/main/comic/ComicLetter.tscn
The warning occurred because the reset method used a different interpolation method.
=> Fixed comic letter interpolation mode warning.

project/src/demo/background-demo-preset.gd, project/src/main/background.gd, project/src/main/card-control.gd, project/src/main/comic-manager.gd, project/src/main/frog-chase-behavior.gd, project/src/main/frog-dance-behavior.gd, project/src/main/frog-give-ribbon-behavior.gd, project/src/main/intermission-panel.gd, project/src/main/level-buttons.gd, project/src/main/level-cards.gd, project/src/main/levels/frodoku-rules.gd, project/src/main/levels/froggo-rules.gd, project/src/main/levels/fruit-maze-rules.gd, project/src/main/levels/maze-rules.gd, project/src/main/levels/pattern-memory-rules.gd, project/src/main/levels/secret-collect-rules.gd, project/src/main/levels/word-find-rules.gd, project/src/main/main-menu-panel.gd, project/src/main/main-menu-title.gd, project/src/main/menu-state.gd, project/src/main/music-control.gd, project/src/main/music-player.gd, project/src/main/ui/menu/level-button-holder.gd, project/src/main/world-decoration-holder.gd
This syntax is shorter and prevents us from misspelling signals.
=> Refactor: Node.connect -> Signal.connect

project/src/main/menu-state.gd, project/src/main/music-player.gd
Before, MusicPlayer was a singleton which automatically started playing music when PlayerData loaded the player's music preference. Now, MainMenu is responsible for playing music, so it doesn't happen in random demos like 'BackgroundDemo'.
=> Music is no longer played in random demos.

project/assets/main/world-data.json, project/project.godot, project/src/main/frog-dance-behavior.gd, project/src/main/gameplay-panel.gd, project/src/main/intermission-panel.gd, project/src/main/main-menu-title.gd, project/src/main/music-player.gd, project/src/main/player-data.gd, project/src/main/utils.gd, project/src/main/world-data.gd, project/src/main/world.gd, project/src/test/test-utils.gd, project/src/test/test-world-data.gd
Having this data centralized makes it easier to add new worlds, and makes it more obvious if we forgot to add something. For example, it made me remember that I haven't added a set of frog dances for the first world.
=> Extracted music, dances, levels into config file

project/src/main/frog-chase-behavior.gd, project/src/main/frog-give-ribbon-behavior.gd
The old code was using SUPER_PANIC_DURATION in a weird way where it only made sense if it was a value slightly under 5.0, defeating the purpose of a constant.
The new code mirrors similar code in the frog-chase-behavior script, and allows SUPER_PANIC_DURATION to be adjusted freely.
=> Refactor: Improve super_panic_duration constant use

project/src/main/comic/comic-page.gd
This flag is useful when editing the comic. We need the panels visible to make changes.
=> Added ComicPage.show_all flag.

project/src/main/card-control.gd, project/src/main/frog-chase-behavior.gd, project/src/main/frog-dance-behavior.gd, project/src/main/frog-give-ribbon-behavior.gd, project/src/main/intermission-panel.gd, project/src/main/levels/frodoku-rules.gd, project/src/main/main-menu-panel.gd
Used lambdas in more places, such as sort_custom parameters or Frodoku's comparison functions.
Changed disconnect/is_connectecd syntax to use method names instead of Callables. Callables are a relic of Godot 3.x and the new syntax is more concise.
=> Refactor: Lambdas, disconnect/is_connected syntax

delint.sh, project/src/demo/BeachBallDemo.tscn, project/src/demo/beach-ball-demo.gd, project/src/main/BeachBall.tscn, project/src/main/beach-ball.gd
In Godot 3.x we used '_on_FooBar()' capitalization. In Godot 4.x we prefer '_on_foo_bar()'.
=> Fixed bad signal method capitalization. Added delint check.

project/src/demo/hand-demo.gd
set_biteable_fingers was removed in 7b11b7bd, but some of these external references were not updated.
=> Removed reference to non-existent 'set_biteable_fingers'

project/src/main/comic/World1ComicPage.tscn
With wider windows, the World1 comic would be aligned to the left and not the center.
=> Fixed World1 comic alignment; wasn't centered

delint.sh
Checks for .import files that don't have a corresponding file without the .import extension in the same folder (does not check the internal source_file property).
=> Added .import check to delint.sh

project/src/main/CardControl.tscn, project/src/main/CardSprite.tscn, project/src/main/Hand.tscn, project/src/main/HugSprite.tscn, project/src/main/RibbonSprite.tscn
CardSprite, HugSprite and RibbonSprite now extend from WiggleSprite. This encourages code reuse and also makes changes easier, like our recent 'unique name' changes where we needed to modify WiggleTimer's scene properties.
=> Refactor: WiggleSprite inheritance

project/src/main/comic/ComicPage.tscn, project/src/main/comic/ComicPanel.tscn, project/src/main/comic/World1ComicPage.tscn, project/src/main/comic/World2ComicPage.tscn, project/src/main/comic/comic-panel.gd
Rewrote comic page scenes to inherit ComicPage, ComicPanel. This reduces the amount of copy/paste code, and reduces the likelihood of bugs from things like layout differences between different manually created scenes.
Rewrote ComicPanel to use Godot 4 'unique name' functionality.
=> Extracted ComicPage.tscn, ComicPanel.tscn

project/src/demo/background-demo-custom-tab.gd
Changing the BackgroundDemo's world in the 'preset' tab now updates the 'custom' tab. This lets us review and edit the color palettes for each world by hopping between the 'preset' and 'custom' tabs.
=> Populate BackgroundDemo 'custom' tab with world data

package.sh
The name 'frog-finder-linux-v1.26.x84_86.zip' is unnecessarily verbose and clunky. The version number should come at the end, but doesn't because of limitations of the Godot editor (1.26 is treated as a file extension, resulting in files with names like '-v1.zip')
The new name is better, and preserves the old conventions as well as conventions followed by other linux games.
=> Rename linux export to match old filename

project/src/demo/LevelRulesDemo.tscn, project/src/main/levels/frodoku-rules.gd, project/src/main/levels/froggo-rules.gd
Enabled unique_name_in_owner flag for LevelRulesDemo's GameState and LevelCards, to allow them to be found by GameplayPanel
Suppressed float precision warnings
Minor FrodokuRules cleanup: whitespace, comments
=> LevelRulesDemo errors. Suppressed warnings. FrodokuRules cleanup.

project/src/main/comic/World1ComicPage.tscn, project/src/main/comic/World2ComicPage.tscn
Godot 4.2.2 introduced Godot #91554
(https://github.com/godotengine/godot/issues/91554), a bug with AnimationPlayer
where AnimationPlaybackTrack doesn't call Play properly on the targeted
AnimationPlayer if the track keyframe is set to 0.
A time of 0.001 works.
=> Godot bug workaround for animation playback tracks

project/src/main/comic/ComicPanel.tscn, project/src/main/comic/comic-panel.gd, project/src/main/comic/default-frame-player-animation-library.tres
When creating a new ComicPanel, the animations couldn't be edited because they were reusing the parent AnimationPlayer's AnimationPlayer. I've added some logic to the ComicPanel script so that when a ComicPanel is opened in the editor, it will duplicate the parent animation library. This lets us reuse the parent animations while still allowing changes.
=> Workaround for 'unique animation library' issue

project/src/main/comic/comic-page.gd
This prevents an issue where the show_all toggle would leave one or two frames invisible, because their panel_modulate property was transparent.
=> ComicPanel.show_all now modifies panel_modulate instead of modulate

project/src/main/comic/comic-panel.gd
Fixed bug where the ComicPanel's 'unique animation library' logic did not duplicate animations. This meant newly created animation libraries would still share animations, and editing one comic would also edit all other comics as well.
=> Bug: Comic animation libraries shared animations

project/src/main/comic/World1ComicPage.tscn, project/src/main/comic/World2ComicPage.tscn, project/src/main/comic/World3ComicPage.tscn
Changed some 'very small AnimationPlayer numbers' to 0.001 instead of using arbitrary values.
Godot #91554 (https://github.com/godotengine/godot/issues/91554) prevents AnimationPlaybackTrack from working with a value of 0, so we use very small numbers. Numbers that are too small (like 0.00001) often cause the same bug, while numbers that are too big (like 0.1) result in visible anomalies, so we've settled on 0.001. Using a consistent number will make it easier to detect and reverse the workaround in Godot 4.3 when the bug is fixed.
Fixed an unusual y coordinate for World1ComicPage.Students1.
=> Made 'very small AnimationPlayer numbers' consistent

delint.sh
Fixed problematic code highlighted by SC2128 (expanding an array without an index only gives the element in the index 0), SC2206 (quote to prevent word splitting/globbing) and SC2068 (double quote array expansions to avoid re-splitting elements)
=> Delint: Shellcheck violations in orphaned import script

project/src/main/dance-animations.gd, project/src/main/frog-dance-library.tres
Before, DanceAnimations.update_dances would add all the 'flip' animations last, which is the order they were written in the .tscn file. Then, Godot would reorder them later, resulting in reordered frog dances appearing in an unrelated commit.
I've added a manual step to explicitly purge the animation library and re-add all of the animations, so that they will be alphabetized.
=> Refactor: DanceAnimations script preserves dance order.

project/src/main/comic/ComicPage.tscn, project/src/main/comic/ComicSkipButton.tscn, project/src/main/comic/World1ComicPage.tscn, project/src/main/comic/World2ComicPage.tscn, project/src/main/comic/World3ComicPage.tscn, project/src/main/comic/comic-page.gd, project/src/main/comic/comic-skip-button.gd
Comic animations no longer explicitly call fade in, fade out, or control the skip button's visibility. This is handled by ComicPage.tscn, ComicSkipButton.tscn.
Before, all of our comic animations call "fade_out" on the last frame, and it caused a bug we had to fix in #315.
=> Refactor: Streamline comic fade in, fade out, skip button
