project/project.godot, project/src/main/CardControl.tscn, project/src/main/MainMenu.tscn, project/src/main/card-control.gd, project/src/main/game-state.gd, project/src/main/gameplay-panel.gd, project/src/main/level-cards.gd, project/src/main/level-rules.gd, project/src/main/main-menu-panel.gd
This level includes the word 'frog' and 'shark' and the player must
click the correct one.
=> Added a simple word level.

project/project.godot, project/src/demo/IntermissionPanelDemo.tscn, project/src/demo/intermission-panel-demo.gd, project/src/main/CardControl.tscn, project/src/main/IntermissionPanel.tscn, project/src/main/MainMenu.tscn, project/src/main/card-control.gd, project/src/main/card-sprite.gd, project/src/main/game-over-panel.gd, project/src/main/game-state.gd, project/src/main/gameplay-panel.gd, project/src/main/intermission-panel.gd, project/src/main/level-cards.gd, project/src/main/main-menu-panel.gd, project/src/main/menu-state.gd, project/src/main/wiggle-timer.gd
Animation tweaks. Flipped card animations always start on a full frame,
instead of being interrupted mid-frame.
=> Added intermission panel. Game ends at ten frogs.

project/src/main/frodoku-level-rules.gd, project/src/main/froggo-level-rules.gd, project/src/main/gameplay-panel.gd, project/src/main/hand.gd, project/src/main/level-cards.gd, project/src/main/main-menu-panel.gd, project/src/main/maze-level-rules.gd, project/src/main/menu-state.gd, project/src/main/secret-collect-level-rules.gd, project/src/main/word-find-level-rules.gd
Secret collect now reveals a sea of frogs if you don't click next to a
cell. It reveals adjacent frogs if you click next to an adjacent face-up
cell.
Frodoku now hides everything except the row/column/region when you fail.
Word find now hides all letters except those in the word 'frog'.
=> Improved feedback when losing 'secret collect', 'frodoku', 'word find'

project/src/main/frodoku-level-rules.gd
This makes it easier for people to spot the patterns. Some had no idea
about the region rule. Some had absolutely no idea whatsoever.
=> On easier difficulties, Frodoku reveals an entire column/row/region

project/project.godot, project/src/main/CuteButton.tscn, project/src/main/MainMenu.tscn, project/src/main/MainMenuPanel.tscn, project/src/main/level-buttons.gd, project/src/main/main-menu-panel.gd, project/src/main/player-data.gd, project/src/main/ui/menu/TutorialButtons.tscn, project/src/main/ui/menu/World1Buttons.tscn, project/src/main/ui/menu/World2Buttons.tscn, project/src/main/ui/menu/level-button-holder.gd, project/src/main/ui/menu/wide-wow-sprite.gd, project/src/main/utils.gd
Can page through different worlds. Three for now.
Minor refactoring of UI logic; things like 'Instructions' and 'LevelButtons' are larger with their mouse mode set to ignore. This avoids potentially weird bugs where you can't click the upper left corner of the music button, for example.
=> Adding paging logic.

project/project.godot, project/src/main/MainMenu.tscn, project/src/main/main-menu-panel.gd, project/src/main/menu-state.gd, project/src/main/music-control.gd, project/src/main/music-player.gd, project/src/main/player-data.gd, project/src/main/ui/menu/clickable-icon.gd, project/src/main/ui/menu/level-button-holder.gd
Many components in the game need access to things like the current music preference or current world, and it's tedious to pass the PlayerData path around to everyone.
=> PlayerData is now an autoload singleton.

project/src/demo/LevelRulesDemo.tscn, project/src/demo/level-rules-demo.gd, project/src/main/froggo-level-rules.gd, project/src/main/gameplay-panel.gd, project/src/main/utils.gd
The first mission of each world uses easier difficulties in the range 0-4. The final mission of each world uses harder difficulties in the range 0-7. The difficulty 8 levels are reserved for specific levels the player's already been tested on before.
Each mission uses different levels now. The first two missions of each world trains the player on two levels. The final mission of each world tests the player on harder versions of five levels.
=> Each mission includes unique levels, difficulties.

project/src/main/MainMenuPanel.tscn, project/src/main/main-menu-panel.gd
Added anchor tags so main menu grows/shrinks appropriately.
=> Main menu grows/shrinks with anchor tags

project/src/demo/LevelRulesDemo.tscn, project/src/main/Background.tscn, project/src/main/CardControl.tscn, project/src/main/IntermissionPanel.tscn, project/src/main/MainMenu.tscn, project/src/main/MainMenuPanel.tscn
Manual workaround for Godot #57862
=> Removed unnecessary _edit_use_anchors_ metadata

project/src/main/running-shark.gd
Sharks have a flanking strategy, but they were trying to flank you even when their flank-buddy had already eaten.
=> Fix bug where sharks wouldn't always chase you

project/src/main/RunningFrog.tscn, project/src/main/frog-chase-behavior.gd
Frogs are now centered at their feet. This makes y-sorting work more intuitively.
=> Adjusted frog offset; feet align with ground

project/src/main/menu-state.gd, project/src/main/music-player.gd
When starting a new level, the ending song should stop. This behavior was broken because the final song 'hug from a frog' awas accidentally added to the list of frog songs.
=> Fixed bug where ending song didn't stop.

project/src/main/frog-arrangements.gd, project/src/main/frog-dance-behavior.gd, project/src/main/menu-state.gd, project/src/main/player-data.gd
The number of dances the player's seen is saved in the 'frog_dance_count' field. As they watch more dances, the number of frogs gradually increases.
=> More frogs appear with each dance.

project/src/main/CardControl.tscn, project/src/main/card-control.gd, project/src/main/intermission-panel.gd
Extracted onready fields for IntermissionPanel/CardControl fields, to avoid unnecessary get_node() calls
Reordered/alphabetized CardControl fields and nodes.
=> Refactor: IntermissionPanel/CardControl onready, reordering

project/src/main/frog-chase-behavior.gd, project/src/main/running-frog.gd, project/src/main/running-shark.gd
Some of these parameters/constants such as 'PINCER_DISTANCE' and 'SUPER_PANIC_DURATION' were not very clear without comments.
=> Additional frog/shark code comments.

project/src/demo/BackgroundDemo.tscn, project/src/demo/MusicPlayerDemo.tscn, project/src/demo/background-demo.gd, project/src/demo/music-player-demo.gd
These functions are behaving strangely after the Godot 4 upgrade, having a demo makes them easier to test.
=> New demos: BackgroundDemo, MusicPlayerDemo

project/export_presets.cfg.template
Game runs on Windows, HTML5. I cannot easily test the iOS or Linux distributions.
=> Updated export presets for Godot 4.

project/src/demo/ControlParallaxerDemo.tscn, project/src/main/ControlParallaxer.tscn, project/src/main/World1Decorations.tscn, project/src/main/World2Decorations.tscn, project/src/main/World3Decorations.tscn, project/src/main/control-parallaxer.gd
I'm trying to separate the clickable items from the non-clickable items to make the UI less confusing.
=> Added parallax motion for menu decorations.

project/src/main/background.gd, project/src/main/card-control.gd, project/src/main/frog-dance-behavior.gd, project/src/main/hand.gd, project/src/main/music-control.gd, project/src/main/music-player.gd, project/src/main/player-data.gd, project/src/main/ui/menu/clickable-icon.gd
This new syntax is consistent with our guidelines for our sister project, Turbo Fat
=> Consistent syntax for godot issues

project/src/main/GameplayPanel.tscn, project/src/main/MainMenu.tscn
Extracted GameplayPanel from MainMenu.tscn
=> Refactor: GameplayPanel scene

delint.sh, project/src/main/card-control.gd, project/src/main/comic-manager.gd, project/src/main/frog-chase-behavior.gd, project/src/main/frog-dance-behavior.gd, project/src/main/intermission-panel.gd, project/src/main/level-buttons.gd, project/src/main/level-cards.gd, project/src/main/levels/frodoku-rules.gd, project/src/main/levels/froggo-rules.gd, project/src/main/levels/fruit-maze-rules.gd, project/src/main/levels/maze-rules.gd, project/src/main/levels/pattern-memory-rules.gd, project/src/main/levels/secret-collect-rules.gd, project/src/main/levels/word-find-rules.gd, project/src/main/main-menu-panel.gd, project/src/main/menu-state.gd, project/src/main/music-control.gd, project/src/main/music-player.gd, project/src/main/ui/cheat-code-detector.gd, project/src/main/ui/menu/level-button-holder.gd, project/src/main/ui/menu/wide-wow-sprite.gd, project/src/main/wiggle-timer.gd, project/src/main/world-decoration-holder.gd
Most of our '...Callable(self...' statements were not horizontally padded with whitespace the same way our other code was. I also added some missing whitespace to CheatCodeDector and Utils.
=> Fixed horizontal whitespace for Callable statements

project/src/demo/BeachBallDemo.tscn
This makes the balls go in front of each other naturally, like they do in the game.
=> Enabled BeachBallDemo ysort.

project/src/demo/beach-ball-demo.gd, project/src/demo/comic-letter-demo.gd, project/src/demo/comic-page-demo.gd, project/src/demo/hand-demo.gd, project/src/demo/intermission-panel-demo.gd, project/src/demo/level-rules-demo.gd
Some of these had keys which were just obviously out of order, like 'd, f, m, s, *H*, t, w'. But for the others, I followed the pattern of letters -> numbers -> special charcters, ordering special characters by ascii code (space, plus/minus, braces)
=> Reordered demo keys.

project/src/main/IntermissionPanel.tscn, project/src/main/beach-ball-tweak.gd, project/src/main/intermission-panel.gd
This 'Creatures' node used to only contain sharks and frogs, but it now contains stuff like beach balls.
=> Renamed 'Creatures' node to 'Obstacles'.

project/src/main/levels/frodoku-rules.gd
If the player clicks EVERY illegal cell, they will find a shark. Before, it was literally impossible to lose on the easiest difficulty. It's still impossible to lose unless you maliciously click all of the wrong cells.
=> Frodoku is always failable, even on the easiest difficulty.

project/src/demo/LevelRulesDemo.tscn, project/src/main/levels/frodoku-rules.gd
Centralized Frodoku's 'compare methods', and replaced them with Callables.
Removed redundant 'revealed_lizard_count' method.
=> Frodoku improvements: compare methods, revealed_lizard_count

project/src/main/MainMenuPanel.tscn, project/src/main/main-menu-panel.gd, project/src/main/main-menu-title.gd
Other worlds can specify their own titles by adding a new entry to MainMenuTitle.titles_by_world_index
=> Sunshine Shoals has its own title.

project/src/main/CardControl.tscn, project/src/main/card-control.gd, project/src/main/comic/comic-letter.gd, project/src/main/wiggle-sprite.gd
It already had logic to avoid shuffling between two wiggle frames. However, some cards have multiple variations, and it was still shuffling between those.
=> Fixed CardControl to avoid randomizing cards.

project/src/demo/background-demo-picker-row.gd, project/src/main/card-arrangements.gd, project/src/main/card-control.gd, project/src/main/comic/comic-letter.gd, project/src/main/comic/comic-page.gd, project/src/main/comic/comic-panel.gd, project/src/main/comic/comic-title.gd, project/src/main/dance-animations.gd, project/src/main/frog-arrangements.gd, project/src/main/frog-chase-behavior.gd, project/src/main/frog-dance-behavior.gd, project/src/main/frog-give-ribbon-behavior.gd, project/src/main/gameplay-panel.gd, project/src/main/hand.gd, project/src/main/levels/level-rules.gd, project/src/main/main-menu-title.gd, project/src/main/player-data.gd, project/src/main/running-frog.gd, project/src/main/running-shark.gd, project/src/main/ui/menu/clickable-icon.gd
I kept around the 'set_state' setter on hand because it was being used outside the class. Other sections of code also call 'set_state' in cases where there's no explicit state variable. I think the existence or absence of a 'state' variable is an implementation detail which is good to hide with a function.
=> Inline most setters.

project/src/main/Background.tscn, project/src/main/BeachBall.tscn, project/src/main/CardControl.tscn, project/src/main/FingerSprite.tscn, project/src/main/IntermissionPanel.tscn, project/src/main/background.gd, project/src/main/beach-ball.gd, project/src/main/card-control.gd, project/src/main/comic/ComicLetter.tscn, project/src/main/comic/ComicTitle.tscn, project/src/main/comic/World1ComicPage.tscn, project/src/main/comic/World2ComicPage.tscn, project/src/main/comic/comic-letter.gd, project/src/main/comic/comic-page.gd, project/src/main/comic/comic-title.gd, project/src/main/finger-sprite.gd, project/src/main/ui/menu/ClickableIcon.tscn, project/src/main/ui/menu/World1Buttons.tscn, project/src/main/ui/menu/World2Buttons.tscn, project/src/main/ui/menu/World3Buttons.tscn, project/src/main/ui/menu/clickable-icon.gd, project/src/main/ui/menu/wide-wow-sprite.gd
Unique names utilize a cache so we don't need to cache them ourselves, cutting down on code.
=> Refactor: Replace some absolute paths with unique names

project/src/demo/BackgroundDemo.tscn, project/src/main/IntermissionPanel.tscn, project/src/main/MainMenu.tscn
This fixes some 'ext_resource, invalid UID: uid://cwayb4utjyh6d' errors.
=> Added missing UIDs

project/export_presets.cfg.template
Minor churn in the export_presets.cfg format. These changes were made by the godot editor. I'm merging these changes separately to avoid churn in meaningful commits
=> Minor export presets changes from Godot

delint.sh, project/src/main/card-arrangements.gd, project/src/main/card-control.gd, project/src/main/frog-arrangements.gd, project/src/main/frog-chase-behavior.gd, project/src/main/frog-dance-behavior.gd, project/src/main/levels/secret-collect-rules.gd
Long line delint script was not escaping its curly braces properly.
=> Fixed long line delint script. Split long lines.

delint.sh
This semicolon-delimited style has become more popular recently.
=> Refactor: Change delint script from 'if x... then' to 'if x; then'
